services:
  - type: web
    name: hub-cpd
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python serve.py
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: PUBLIC_URL
        value: https://hub-cpd.co.uk
      - key: DEBUG
        value: "false"
      - key: FEEDBACK_SHARE_COPD_LIVE
        sync: false
      - key: FEEDBACK_SHARE_HF_LIVE
        sync: false
      - key: HOST_TOKEN
        generateValue: true
  - type: web
    name: hub-cpd-test
    runtime: python
    region: frankfurt
    plan: free
    branch: heart-failure-cpd
    buildCommand: pip install -r requirements.txt
    startCommand: python serve.py
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: PUBLIC_URL
        value: https://hub-cpd-test.onrender.com
      - key: DEBUG
        value: "true"
      - key: FEEDBACK_SHARE_COPD_DEV
        sync: false
      - key: FEEDBACK_SHARE_HF_DEV
        sync: false
      - key: HOST_TOKEN
        generateValue: true
  - type: web
    name: copd-cpd
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python serve.py
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DEBUG
        value: "false"
